/*
PROJETO DO SEGUNDO SEMESTRE DE CIÊNCIA DA COMPUTAÇÃO
NOMES:   CAROLINA BREITENWIESER RA00222650
         CAROLINE UEHARA  RA00222619
         ZEYNEP SALIHOGLU RA00227219  
*/     
#include "model.h"
#include <string.h>
#include <stdio.h>

#endif /* MODEL_H_ */
